#!/usr/bin/env bash

# Summary: Installs a plugin
source "${DOTFILES_DIR}/lib/helpers"

if [ "$#" -ne 3 ]
then
  echo "Usage: dotfiles-install-plugin <PLUGIN_GIT_URL>"
  exit 1
fi

PLUGIN_URL=$3
PLUGIN_DIR="$DOTFILES_DIR/plugins"
PLUGIN=$(basename $PLUGIN_URL | sed 's/.git$//')

if [ -d $PLUGIN_DIR/$PLUGIN ]; then
    debug_msg "Removing folder $PLUGIN_DIR/$PLUGIN to reinstall"
    rm -rf $PLUGIN_DIR/$PLUGIN
fi

debug_msg "Installing $PLUGIN"
git clone $PLUGIN_URL "$PLUGIN_DIR/$PLUGIN" -v
cd $DOTFILES_DIR && make setup
cd -

if [[ $? != 0 ]]
then
    fail_msg "Failed to Install $PLUGIN"
fi

