#!/usr/bin/env bash

# Summary: Search for all install.sh inside DOTFILES_ROOT and execute it
#
# Search for all install.sh inside DOTFILES_ROOT and execute it

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
source "${DOTFILES_ROOT}/lib/helpers"

execute_installers_from_path () {
  install_paths=$1

  for installer in $install_paths
  do
      debug_msg "Install $installer"
      sh -c "$installer"

      if [[ $? != 0 ]]
      then
          fail_msg "Failed to Install $installer"
      fi
  done

}

install_filepaths=$(find -H "$DOTFILES_ROOT" -type f -name "install.sh" -not -path "$DOTFILES_ROOT/plugins/*")
install_plugins_filepaths=$(find -H "$DOTFILES_ROOT" -type f -name "install.sh" -path "$DOTFILES_ROOT/plugins/*")
debug_msg "Paths founded:\n$install_filepaths\n$install_plugins_filepaths"

execute_installers_from_path $install_filepaths
execute_installers_from_path $install_plugins_filepaths
