#!/usr/bin/env bash

# Summary: Update a plugin

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
PLUGINS_DIR=$DOTFILES_ROOT/plugins
ORIGINAL_FOLDER=$PWD

source "${DOTFILES_ROOT}/lib/helpers"

if [ $# -ne 3 ];then
    echo "Usage: dotfiles update-plugin <PLUGIN_NAME>"
    exit -1
fi

PLUGIN=$3

if [ ! -d ${PLUGINS_DIR}/$PLUGIN ];then
    fail_msg "Plugin $PLUGIN not found"
fi

debug_msg "Updating $PLUGIN"
cd $PLUGINS_DIR/$PLUGIN
ACTUAL_BRANCH=$(git branch --show-current)
git pull origin ${ACTUAL_BRANCH}
cd $ORIGINAL_FOLDER
make -f $DOTFILES_ROOT/Makefile setup-no-reload

if [[ $? != 0 ]]
then
    fail_msg "Failed to update $PLUGIN"
fi

success_msg "Plugin $PLUGIN updated successfully"
zsh -l
