#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary: Display version of dotfiles

DOTFILES_ROOT=$1
DOTFILES_DEBUG=$2

# Needs to load the helpers before using it
source "${DOTFILES_ROOT}/lib/helpers"

echo "dotfiles $(_get_dotfiles_version)"
