#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary: Add all "bin" folders inside the DOTFILES_ROOT to the $PATH

DOTFILES_ROOT=$1
DOTFILES_DEBUG=$2

# Needs to load the helpers before using it
source "${DOTFILES_ROOT}/lib/helpers"

add_bin_files_to_path () {
    set_debug_file_label "$BASH_SOURCE"

    info_msg 'Add all files inside bin directory to the $PATH'

    local overwrite_all=false backup_all=false skip_all=false

    bin_filepaths=$(find -H "$DOTFILES_ROOT" -type f -maxdepth 5 -path "**/bin/*" ! -name 'README.md')
    debug_msg "Paths found: $bin_filepaths"

    for src in $bin_filepaths
    do
        dst="/usr/local/bin/$(basename ${src})"
        _link_file "$src" "$dst" "$overwrite_all" "$backup_all" "$skip_all"
    done
}

add_bin_files_to_path
