#!/usr/bin/env bash

# Summary: Uninstalls a plugin

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"

source "${DOTFILES_ROOT}/lib/helpers"
PLUGIN=$3

debug_msg "Uninstall $PLUGIN"
rm -rf "$DOTFILES_ROOT/plugins/$PLUGIN"
make -f $DOTFILES_ROOT/Makefile setup

if [[ $? != 0 ]]
then
    fail_msg "Failed to Install $PLUGIN"
fi

