#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary: Search for all install.sh inside DOTFILES_ROOT and execute it
#
# Search for all install.sh inside DOTFILES_ROOT and execute it

PLUGINS_DIR=$DOTFILES_ROOT/plugins

execute_installers_from_path () {
  install_paths=$1

  for installer in $install_paths
  do
      info_msg "Installing $installer:"
      DOTFILES_ROOT=$DOTFILES_ROOT DOTFILES_DEBUG=$DOTFILES_DEBUG sh -c "$installer"

      if [[ $? != 0 ]]
      then
          fail_msg "Failed to install $installer"
      fi
  done
}

install_filepaths=$(find -H "$DOTFILES_ROOT" -type f -name "install.sh" -not -path "$PLUGINS_DIR/*")
install_plugins_filepaths=$(find -H "$DOTFILES_ROOT" -type f -name "install.sh" -path "$PLUGINS_DIR/*")
debug_msg "Paths founded:\n$install_filepaths\n$install_plugins_filepaths"

# Only install scripts inside core folder
execute_installers_from_path "${install_filepaths[@]}"

# Install scripts inside plugins folder
execute_installers_from_path "${install_plugins_filepaths[@]}"
