#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary: List all plugins installed

DOTFILES_ROOT=$1
DOTFILES_DEBUG=$2
PLUGINS_DIR=$DOTFILES_ROOT/plugins

# Needs to load the helpers before using it
source "${DOTFILES_ROOT}/lib/helpers"

for plugin in `ls -1 $PLUGINS_DIR`;do
  if [ -d $PLUGINS_DIR/$plugin ];then
    cd $PLUGINS_DIR/$plugin
    plugin_url=$(git remote get-url origin)
    echo "$plugin: $plugin_url"
    cd $PLUGINS_DIR 2>/dev/null
  fi
done

if [[ $? != 0 ]]
then
    fail_msg "Failed to list plugins installed"
fi

