#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary:
# 1. Search for all install.sh files and execute it.
# 2. Search for all *.symlink and create symbolic links into $HOME
# 3. Search for all executables inside "bin" folders made it available from $PATH.

# Needs to load the helpers before using it
source "${DOTFILES_ROOT}/lib/helpers"

debug_msg "Reloading the dotfiles"

dotfiles-symlink $DOTFILES_ROOT $DOTFILES_DEBUG
dotfiles-install $DOTFILES_ROOT $DOTFILES_DEBUG
dotfiles-bin-path $DOTFILES_ROOT $DOTFILES_DEBUG

success_msg "Dotfiles reloaded"
