#!/usr/bin/env bash

# Summary: Installs a plugin

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
source "${DOTFILES_ROOT}/lib/helpers"
PLUGIN=$1

debug_msg "Install $PLUGIN"
git -C ./plugins clone "https://gitlab.com/autentia/internal/dotfiles/dotfiles-$PLUGIN"
cd "dotfiles-$PLUGIN" && make setup

if [[ $? != 0 ]]
then
    fail_msg "Failed to Install $PLUGIN"
fi

