#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

echo "Usage: dotfiles <command> [<options>]

Dotfiles tool will manage installation and configuration.

Commands:
   install                                 Search for all install.sh files and execute it
   install-plugin <DOTFILES_GIT_URL>       Install a given plugin, it take the git repository of the plugin as the parameter
   update-plugin <PLUGIN_NAME>             Update a given plugin
   uninstall-plugin <PLUGIN_NAME>          Uninstall a given plugin
   create-plugin <PLUGIN_NAME>             Create a plugin using the base template
   plugins                                 Shows all plugins installed
   update                                  Update to latest version of dotfiles
   uninstall                               Search for all uninstall.sh files and execute it
   apply                                   Search for all install.sh files and execute it.
                                           Search for all *.symlink and create symbolic links into \$HOME
                                           Search for all executables inside 'bin' folders and make it available from \$PATH.
   version                                 Display the version
"
