#!/usr/bin/env bash
# Summary: Display version of dotfiles

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
source "${DOTFILES_ROOT}/lib/helpers"

echo "dotfiles $(_get_dotfiles_version)"
