#!/usr/bin/env bash
# Summary: Symlink

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
source "${DOTFILES_ROOT}/lib/helpers"
source "${DOTFILES_ROOT}/lib/symlink-helpers"

create_symlinks
