#!/usr/bin/env bash

# Doesn't add set -u to have better validation of undefined input variables.
set -eo pipefail
IFS=$'\n\t'

# Summary: Update a plugin
#
# Options:
#   --skip-deps-installation  Skip installing dependencies (Homebrew) while still
#                             applying the rest of the configuration.

PLUGINS_DIR=$DOTFILES_ROOT/plugins
ORIGINAL_FOLDER=$PWD
PLUGIN=""

for arg in "$@"; do
  case "$arg" in
    --skip-deps-installation)
      export DOTFILES_SKIP_DEPS_INSTALLATION="true"
      ;;
    *)
      PLUGIN="$arg"
      ;;
  esac
done

if [ -z "$PLUGIN" ];then
  fail_msg "Missing plugin name.\nUsage: dotfiles update-plugin <PLUGIN_NAME> [--skip-deps-installation]"
  exit 1
fi

if [ ! -d ${PLUGINS_DIR}/$PLUGIN ];then
  fail_msg "Plugin $PLUGIN not found"
fi

debug_msg "Updating $PLUGIN"
cd $PLUGINS_DIR/$PLUGIN
ACTUAL_BRANCH=$(git branch --show-current)
git pull origin ${ACTUAL_BRANCH}
cd $ORIGINAL_FOLDER
make -f $DOTFILES_ROOT/Makefile setup-no-reload

if [[ $? != 0 ]]
then
  fail_msg "Failed to update $PLUGIN"
fi

success_msg "Plugin $PLUGIN updated successfully"
zsh -l
