#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Summary: Search for all uninstall.sh inside DOTFILES_ROOT and execute it
#
# Search for all uninstall.sh inside DOTFILES_ROOT and execute it

source "${DOTFILES_ROOT}/lib/uninstall-helpers"

exec_uninstall_scripts $DOTFILES_ROOT $DOTFILES_DEBUG
