#!/usr/bin/env bash

# Summary: Search for all uninstall.sh inside DOTFILES_ROOT and execute it
#
# Search for all uninstall.sh inside DOTFILES_ROOT and execute it

DOTFILES_ROOT="${1:?Usage: dotfiles-bin-path DOTFILES_ROOT_PATH}"
source "${DOTFILES_ROOT}/lib/helpers"
source "${DOTFILES_ROOT}/lib/uninstall-helpers"

exec_uninstall_scripts $DOTFILES_ROOT
