#!/usr/bin/env bash
# Summary: Display version of dotfiles
#
# Displays the version number 

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


git_latest_version="$(git describe --tags HEAD 2>/dev/null || true)"
echo "dotfiles ${git_latest_version:-0.1.0}"
